### PR TITLE
preparing for release

### PR DESCRIPTION
**Pull request by grosser**

### CODE REVIEW

**Comment by rtomayko** [comment]
Looks good :+1:

I'm flipping travis CI on now.

**Comment by akuhn** [comment]
This just broken our internal build. Tightening the requirements on ruby version should ideally only happen with a major version bump.

**Comment by grosser** [comment]
it's not a change of behavior ... so it should not break anything ...
how did you get it installed if it is not working on that ruby version ?

**Comment by akuhn** [comment]
Rack cache is a dependency of rails, requiring Ruby 2.0 in rack-cache impacts the installation dependencies of rails. We use rails 3.2.22 which requires actionmailer 3.2.22 which requires actionpack 3.2.22 which requires rack-cache `~> 1.2` and then fails because it attempts to install version 1.3 that requires Ruby 2.0.

**Comment by grosser** [comment]
added 1.9 support in 1.3.1

**Pull request merged**
