### PR TITLE
do not read replies we already have from the cache

### PR DESCRIPTION
**Pull request by grosser**
@amatriain @rtomayko 

no idea why this is there ...

### CODE REVIEW

**Comment by grosser** [comment]
@alau you got any idea why we do this ?

**Comment by grosser** [comment]
found an old comment `read existing cache entries, adding this one to the list`

**Comment by grosser** [comment]
`I'm assuming that this is because we want to use IO-streams or
something from the backing store, and that it does not apply in this case.`

**Comment by grosser** [comment]
only Disk seems to be doing anything fancy there ... and I don't understand why a IO object would be any better then a string we already have ...

**Comment by amatriain** [comment]
I don't know why we would want to change the response body on a cache miss, either. The presence of a cache should be transparent if the cache is missed, except for the addition of the X-Rack-Cache header.

What Disk does makes sense when restoring a response from the cache (breaking the string in 8K chunks so that the body responds to ```each```), but not so much when storing the response in the cache.

+1 to merging this.

**Comment by alau** [comment]
> @alau you got any idea why we do this ?

I have not kept track of the changes to this project since https://github.com/rtomayko/rack-cache/pull/66 . Given that the test about gracefully degrading when the cache store goes offline still passes, the removed lines don't seem to be needed for that behavior anymore.

**Comment by grosser** [comment]
Got a mail ok from @rtomayko so let's do this :)

**Comment by grosser** [comment]
v1.6.0 :pray:

**Comment by grosser** [comment]
yanked 1.6.0 because of https://github.com/rtomayko/rack-cache/issues/134#issuecomment-182580311

**Pull request merged**
